Also catch NoClassDefFoundError and ExceptionInInitializerError, so it can run even without a mircoprofile-config implementation; simplified code (`disableExecutions` should have been `enableExecutions`)